learned about shellcheck

diff --git a/pup b/pup
--- a/pup
+++ b/pup
@@ -4,46 +4,53 @@
 grn="\033[0;32m"
 ylw="\033[0;33m"
 red="\033[0;31m"
-res="\033[0m" # reset colors
+res="\033[0m" # reset color
 
-# Status messages
 pup_ok=$(printf "%b" "${grn}pup:${res}")
 pup_bad=$(printf "%b" "${red}pup:${res}")
 pup_wrn=$(printf "%b" "${ylw}pup:${res}")
 
-read -p "${pup_ok} Have you checked for problematic updates? [y/N]: " informed
+today="$(date +%A)"
+update_day="Friday"
 
-# get it ??? pup ??? vet ??? checkup ??? i am a genius.
+if [[ "${today}" == "${update_day}" || "$1" == "--force" ]]; then
+    read -rp "${pup_ok} Have you checked for problematic updates? [y/N] " informed
+else
+    echo "${pup_bad} Update day is set to ${update_day}!"
+    exit 1
+fi
+
+
 function _vet {
-  local upd_msg=$(echo "Updating packages with '${@}'…")
+    local upd_msg
+    upd_msg=$(printf "%s %s " "Updating packages with:" "${@}")
 
-  echo "${pup_ok} ${upd_msg}"
-  "${@}"
+    echo "${pup_ok} ${upd_msg}"
+    "${@}"
 
-  # Error handling
-  local exit_status=${?}
-  [[ ${exit_status} == 0 ]] ||
-    (echo "${pup_bad} '${@}' failed with exit status '${exit_status}'." &&
-    exit 1)
+    # Error handling
+    local exit_status=${?}
+    [[ ${exit_status} == 0 ]] ||
+        (printf "%s %s %s " "${pup_bad}" "${@}" "failed with exit status ${exit_status}." &&
+        exit 1)
 }
 
 # Main program
 case ${informed} in
-  "y"|"Y"|"sure did"|"yup") 
-    paru_arr=(paru -Syu --noconfirm)
-    fp_arr=(flatpak update --user --assumeyes)
-
-    _vet "${paru_arr[@]}"
-    _vet "${fp_arr[@]}"
-    echo "${pup_ok} Done! :D"
-
-    exit 0
-    ;;
-  *)
-    echo "${pup_wrn} No packages were updated. Read the news! >:c"
-    echo ""
-    paru -Pw
-
-    exit 0
-    ;;
+    "y"|"Y"|"sure did"|"yup"|"yes"|"Yes"|"you're not my dad bro") 
+        paru_arr=(paru -Syyuu)
+        fp_arr=(flatpak update --user)
+        tldr_arr=(tldr --update)
+        _vet "${paru_arr[@]}"
+        _vet "${fp_arr[@]}"
+        _vet "${tldr_arr[@]}"
+        echo "${pup_ok} Done! :D"
+        exit 0
+        ;;
+    *)
+        echo "${pup_wrn} No packages were updated. Read the news!"
+        echo "${pup_wrn} Fetching news…"
+        paru -Pw
+        exit 0
+        ;;
 esac
